/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabio
 */
public class FrmVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVendas
     */
    public FrmVendas() {
        initComponents();
        FrmVendas.tabelaVendas.getTableHeader().setDefaultRenderer(new principal
                .EstiloTabelaHeader());
        FrmVendas.tabelaVendas.setDefaultRenderer(Object.class, new principal
                .EstiloTabelaRenderer());
                
        //list all records
        FrmVendas.tabelaVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        limparCampos();        
    }
    
    void limparCampos(){
        if (tabelaVendas.getSelectedRow() > -1) {
            tabelaVendas.removeRowSelectionInterval(tabelaVendas.getSelectedRow(),
                    tabelaVendas.getSelectedRow());
        }
        dtcData.setDate(null);
        fldBuscar.setText("");
        VendasSql.listar("");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelVendas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        painelOpcoes = new javax.swing.JPanel();
        fldBuscar = new app.bolivia.swing.JCTextField();
        lblBuscar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnElimTudo = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnBuscData = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        btnVendasHoje = new javax.swing.JButton();
        dtcData = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setTitle("VENDAS");

        painelVendas.setBackground(new java.awt.Color(255, 255, 255));

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO VENDA", "TOTAL", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabelaVendas);

        painelOpcoes.setBackground(new java.awt.Color(255, 255, 255));
        painelOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        painelOpcoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fldBuscar.setBackground(new java.awt.Color(34, 102, 145));
        fldBuscar.setBorder(null);
        fldBuscar.setForeground(new java.awt.Color(255, 255, 255));
        fldBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fldBuscar.setOpaque(false);
        fldBuscar.setPhColor(new java.awt.Color(255, 255, 255));
        fldBuscar.setPlaceholder("NÚMERO VENDA");
        fldBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fldBuscarMouseClicked(evt);
            }
        });
        fldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fldBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldBuscarKeyTyped(evt);
            }
        });
        painelOpcoes.add(fldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, -1));

        lblBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/buscarL.png"))); // NOI18N
        painelOpcoes.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, 52));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar1.png"))); // NOI18N
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        btnElimTudo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnElimTudo.setForeground(new java.awt.Color(0, 0, 0));
        btnElimTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT1.png"))); // NOI18N
        btnElimTudo.setText("Eliminar Tudo");
        btnElimTudo.setBorder(null);
        btnElimTudo.setBorderPainted(false);
        btnElimTudo.setContentAreaFilled(false);
        btnElimTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElimTudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElimTudo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT1.png"))); // NOI18N
        btnElimTudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnElimTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimTudoActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnElimTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar Campos");
        btnLimpar.setBorder(null);
        btnLimpar.setBorderPainted(false);
        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar1.png"))); // NOI18N
        btnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btnBuscData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF1.png"))); // NOI18N
        btnBuscData.setToolTipText("Buscar");
        btnBuscData.setBorder(null);
        btnBuscData.setBorderPainted(false);
        btnBuscData.setContentAreaFilled(false);
        btnBuscData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscData.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF2.png"))); // NOI18N
        btnBuscData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscDataActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnBuscData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        lblData.setForeground(new java.awt.Color(153, 153, 153));
        lblData.setText("Data");
        painelOpcoes.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        btnVendasHoje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVendasHoje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/vendasH.png"))); // NOI18N
        btnVendasHoje.setToolTipText("Buscar");
        btnVendasHoje.setBorder(null);
        btnVendasHoje.setBorderPainted(false);
        btnVendasHoje.setContentAreaFilled(false);
        btnVendasHoje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendasHoje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendasHoje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/vendasH1.png"))); // NOI18N
        btnVendasHoje.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVendasHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasHojeActionPerformed(evt);
            }
        });
        painelOpcoes.add(btnVendasHoje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        dtcData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        painelOpcoes.add(dtcData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, 30));

        javax.swing.GroupLayout painelVendasLayout = new javax.swing.GroupLayout(painelVendas);
        painelVendas.setLayout(painelVendasLayout);
        painelVendasLayout.setHorizontalGroup(
            painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelVendasLayout.setVerticalGroup(
            painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(painelOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fldBuscarMouseClicked
        dtcData.setDate(null);
        VendasSql.listar("");
    }//GEN-LAST:event_fldBuscarMouseClicked

    private void fldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldBuscarKeyReleased
        VendasSql.listar(fldBuscar.getText());
    }//GEN-LAST:event_fldBuscarKeyReleased

    private void fldBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldBuscarKeyTyped

    }//GEN-LAST:event_fldBuscarKeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnElimTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimTudoActionPerformed

    }//GEN-LAST:event_btnElimTudoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBuscDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscDataActionPerformed

    }//GEN-LAST:event_btnBuscDataActionPerformed

    private void btnVendasHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasHojeActionPerformed

    }//GEN-LAST:event_btnVendasHojeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscData;
    private javax.swing.JButton btnElimTudo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVendasHoje;
    private com.toedter.calendar.JDateChooser dtcData;
    private app.bolivia.swing.JCTextField fldBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblData;
    private javax.swing.JPanel painelOpcoes;
    private javax.swing.JPanel painelVendas;
    public static javax.swing.JTable tabelaVendas;
    // End of variables declaration//GEN-END:variables
}
