/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author Fabio Luis Guia da Conceção
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }
    
    public JProgressBar getJProgressBar(){
        return progresso;
    };
    
    public JLabel getJLabel(){
        return lblCarregandor;
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelProgress = new javax.swing.JPanel();
        lblCarregandor = new javax.swing.JLabel();
        progresso = new javax.swing.JProgressBar();
        painelGeral = new javax.swing.JPanel();
        lblImgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto de Vendas");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 520));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelProgress.setOpaque(false);

        lblCarregandor.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCarregandor.setText("Carregando Sistema");
        lblCarregandor.setName("lblCarregador"); // NOI18N
        lblCarregandor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarregandorMouseClicked(evt);
            }
        });

        progresso.setName("progresso"); // NOI18N

        javax.swing.GroupLayout painelProgressLayout = new javax.swing.GroupLayout(painelProgress);
        painelProgress.setLayout(painelProgressLayout);
        painelProgressLayout.setHorizontalGroup(
            painelProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProgressLayout.createSequentialGroup()
                .addComponent(lblCarregandor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelProgressLayout.createSequentialGroup()
                .addComponent(progresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelProgressLayout.setVerticalGroup(
            painelProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProgressLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCarregandor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(painelProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 320, 60));

        painelGeral.setLayout(new java.awt.GridLayout(1, 0));

        lblImgFundo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblImgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/splash1.jpg"))); // NOI18N
        painelGeral.add(lblImgFundo);

        getContentPane().add(painelGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCarregandorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarregandorMouseClicked
      Login tela = new Login();  
      tela.setLocationRelativeTo(null);
      tela.setVisible(true);
    }//GEN-LAST:event_lblCarregandorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SplashScreen tela = new SplashScreen();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCarregandor;
    private javax.swing.JLabel lblImgFundo;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelProgress;
    private javax.swing.JProgressBar progresso;
    // End of variables declaration//GEN-END:variables
}
